CREATE TABLE IF NOT EXISTS enlaces (
  id TEXT PRIMARY KEY,
  url TEXT NOT NULL,
  first_seen TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS detalle_raw (
  id TEXT PRIMARY KEY,
  url TEXT NOT NULL,
  data JSONB NOT NULL,
  timestamp TIMESTAMP NOT NULL,
  inserted_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS duplicados (
  id TEXT PRIMARY KEY,
  url TEXT NOT NULL,
  count INTEGER NOT NULL DEFAULT 1,
  first_seen TIMESTAMP NOT NULL,
  last_seen TIMESTAMP NOT NULL
);
